### ISSUE TITLE
Undefined queryresult in Listeners 

### ISSUE THREAD

**Issue by pana800** [jac459/metadriver#1]
`"listeners" : {
      "MoodeStatus" : {"type":"http-get", "command":"http://moode.local:81/current", "pooltime":"5000", "poolduration":"", "queryresult" : "$.song.file", 
        "evalwrite" : [ 
            {"variable" : "CurrentSong", "value" : "$Result"}, 
            {"variable" : "AlbumCoverURI", "value" : "http://moode.local/coverart.php/$Result"}
          ]
        }
	},
 "labels":{
      "CurrentStatus" : {"label":"status", "listen":"SongStatus"},
	  "CurrentSong": {"label":"playing", "listen":"CurrentSong"}
    },`
Can not get the 'listenned' value. The GET command works ok in button press if used

**Comment by jac459** [comment]
Dear Pana, can you pkease tell me if the bug has been corrected in the new version?
