### ISSUE TITLE
listeners

### ISSUE THREAD

**Issue by GekoCH** [jac459/metadriver#5]
pls make the "listeners" feature also http-post compatible

**Comment by jac459** [comment]
Thanks, I will check.

**Comment by jac459** [comment]
Hello, I figured out the issue.
Actually http-post (as well as http-get) are being deprecated and replaced by the following grammar
command":"{\"verb\":\"put\",\"call\":\"http://$HueBridgeIp/api/$HueUserName/lights/$LightNumber/state/"} 
This grammar is marginally more complex but allows to support any verb of Rest (currently get, post, put as I don't see any use for delete for example)
So basically you can use the post this way with listeners. 
I am closing the issue but please don't hesitate to reopen if I missed something.

**Comment by jac459** [comment]
I forgot to mention that your command type will be http-rest.
You can find example of it in the hue drivers.
